{{- $releaseLabels := include "project-onboarding.labels" . -}}
{{- $gitopsNamespace := .Values.namespace -}}
{{- range $key, $apps := .Values.apps}}
{{- range $namespace := $apps.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    {{- $releaseLabels | nindent 4 }}
    argocd.argoproj.io/managed-by: {{$gitopsNamespace}}
{{- end }}
{{- end }}
