{{- $releaseLabels := include "project-onboarding.labels" . -}}
{{- $gitopsNamespace := .Values.namespace -}}
{{- range $key, $apps := .Values.apps}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{$key}}
  namespace: {{$gitopsNamespace}}
  labels:
    {{- $releaseLabels | nindent 4 }}
spec:
  description: {{$key}}
  sourceRepos:
    {{- with $apps.sourceRepos }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    - {{$apps.tenantGitops.repo}}
    - {{$apps.helmChartRepo}}
  destinations:
    - name: {{ $gitopsNamespace }}
      namespace: {{ $gitopsNamespace }}
      server: "https://kubernetes.default.svc"
  {{- range $index,$namespace := $apps.namespaces }}
    - name: {{ $namespace }}
      namespace: {{ $namespace }}
      server: "https://kubernetes.default.svc"
  {{- end }}
  orphanedResources:
    warn: false
  permitOnlyProjectScopedClusters: false
  sourceNamespaces:
  {{- range $namespace := $apps.namespaces }}
    - {{ $namespace }}
  {{- end }}
{{- end }}
