---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - ../../../components/crossplane-chart/

helmCharts:
  - name: crossplane
    releaseName: crossplane
    namespace: crossplane-system
    repo: https://charts.crossplane.io/stable
    version: "1.16.0"
    valuesInline:
      securityContextCrossplane: {}
      provider:
        packages:
          - "xpkg.upbound.io/upbound/provider-azure-management:v1.1.0"
          - "xpkg.upbound.io/upbound/provider-azure-network:v1.1.0"
          - "xpkg.upbound.io/upbound/provider-azure-storage:v1.2.0"

patches:
  - target:
      kind: Deployment
      name: crossplane
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext
        value: {}
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value: {}
  - target:
      kind: Deployment
      name: crossplane-rbac-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext
        value: {}
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value: {}
