---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd-tools
resources:
  - ./namespace.yaml
  - ./pgsql-cluster.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./route.yaml
