---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../../../bases/vault-chart/

helmCharts:
  - name: vault
    releaseName: vault
    namespace: hashicorp
    repo: https://helm.releases.hashicorp.com
    version: 0.25.0
    valuesInline:
      server:
        route:
          enabled: true
        dataStorage:
          storageClass: nfs

patches: []
