namespace: ""
team: ""
apps: []
# apps:
#   app-name:
#     namespaces:
#       - namespace-dev
#       - namespace-qa
#     sourceRepos:
#       - https://helm.github.io/examples
#     tenantGitops:
#       repo: https://github.com/idp-team/team-a-gitops.git
#       path: dev-acm
#     helmChartRepo: https://github.com/idp-team/helm-charts
