---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../bases/vault-config-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: alpha
    target:
      kind: Subscription
  - patch: |-
      - op: replace
        path: /spec/config/env/0/value
        value: http://vault.vault.svc:8200
    target:
      kind: Subscription
