apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cluster-registration.labels" . | nindent 4 }}
spec:
  clusterName: {{ .Release.Name }}
  clusterNamespace: {{ .Release.Name }}
  clusterLabels:
    cloud: BareMetal
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
