---
apiVersion: v1
baseDomain: v3socp.boo
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: dev-acm
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.30.30.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  baremetal:
    apiVIPs:
      - "10.30.30.145"
    ingressVIPs:
      - "10.30.30.146"
pullSecret: ""
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEmAVZWnLeKQkHVuD5U0L2JOacFNBhn9m4tMXqN3/hUMRKSs9LvVkReFCSdOE0jmEZAEbLfExIbEzMhvYDcSJvXpHtHFYzlXADRL6IjqCv7XcuP6Ps/HQlRHmU57Y7OakB98Sv6LqyxPLq+gzVltXvwjjVZQU/ETqTdoe2tGTwFHRedzVATN/9YREMaSwY3XyP33g+lQiyztRDiLDq9fmw9PJ513E/EObuZ3J0iCcJYpGRlngm6Nqc7525mUIo5zsDcGaLh9STl1OXaeLQaNCcHrXazv1J9awrDpM/WyTDT0btVmZil7X2p7xyCGTxxW2WP9+f49Nq38S0uU3o8MYtbN/1Ok+3QsS2MtwmONy3cpOpoOZreUgU6mw4mqxVxd240ALd1aXqEXJr728fMFRrKu9xqqde4VWYJcaqOAT3AIm6jBdpZ1UXepxp/qoVDw5AXvfdjCs5/x3sPIGv8mZ7l0ElbK0nzZhUNI4VL8Fl2olooRCi4PdMk2U1+3eQHDc= vikaspogu@vpogu-mac
